%% Script to test RRT and collision detection
clc, clear, close all

load C:\Users\lfichera\'OneDrive - Worcester Polytechnic Institute (wpi.edu)'\3-simulation.mat

figure
scatter3(qList(1,:), qList(2,:), qList(3,:), 'filled');
hold on
grid on
xlabel('Pull-wire displacement [m]');
ylabel('Axial rotation [rad]');
zlabel('Axial translation [m]');
xlim([0 16e-4]);
%zlim([0.002 10e-3]);
title('Configurations generated by RRT');
view(0,0);

